# Generated by Django 5.2.5 on 2025-10-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_title', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('MT', 'Mid-Term'), ('FN', 'Final'), ('OT', 'Other')], max_length=2)),
                ('academic_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('class_selection', models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=20)),
                ('shift_selection', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day')], max_length=50)),
                ('stream', models.CharField(choices=[('SC', 'Science'), ('AR', 'Arts'), ('CM', 'Commerce'), ('VT', 'Vocational')], default='SC', max_length=2)),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('fridaday', 'Friday')], max_length=10)),
                ('time_slot', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('exam_hall', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
