# Generated by Django 5.2.5 on 2026-09-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_create_subject', '0001_initial'),
        ('academic_mm_class_and_section', '0001_initial'),
        ('exam_mm_exam_setup', '0002_examname_examsetup_delete_exm_mm_exam_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Exam full mark (e.g. 100.00)', max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routiness', to='academic_mm_class_and_section.academicclass')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routinesss', to='exam_mm_exam_setup.examname')),
                ('exam_setup', models.ForeignKey(blank=True, help_text='Automated reference to the configured exam setup', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_routines', to='exam_mm_exam_setup.examsetup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routiness', to='academic_create_subject.subject_name')),
            ],
            options={
                'ordering': ['exam_date', 'id'],
            },
        ),
    ]
