# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_create_subject', '0001_initial'),
        ('academic_mm_class_and_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAdmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('roll_number', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('non paid', 'Non Paid')], max_length=20)),
                ('exam_type', models.CharField(choices=[('MT', 'Mid-Term'), ('FN', 'Final'), ('OT', 'Other')], max_length=2)),
                ('class_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.academicclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examsadmit', to='academic_create_subject.subject_name')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_title', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('MT', 'Mid-Term'), ('FN', 'Final'), ('OT', 'Other')], max_length=2)),
                ('academic_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('shift_selection', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day')], max_length=50)),
                ('stream', models.CharField(choices=[('SC', 'Science'), ('AR', 'Arts'), ('CM', 'Commerce'), ('VT', 'Vocational')], default='SC', max_length=2)),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('fridaday', 'Friday')], max_length=10)),
                ('time_slot', models.CharField(max_length=50)),
                ('exam_hall', models.CharField(max_length=50)),
                ('class_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.academicclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examsss', to='academic_create_subject.subject_name')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
