# Generated by Django 5.2.5 on 2026-09-13 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_exmroutine_exmadmit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examroutine',
            options={'ordering': ['exam_date', 'start_time', 'id']},
        ),
        migrations.AddField(
            model_name='examroutine',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Exam end time (e.g. 13:00:00)', null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Exam start time (e.g. 10:00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
