# Generated by Django 5.2.5 on 2025-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_exmroutine_exmadmit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAdmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('roll_number', models.IntegerField(max_length=20)),
                ('class_selection', models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=20)),
                ('subject', models.CharField(max_length=250)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('non paid', 'Non Paid')], max_length=20)),
                ('exam_type', models.CharField(choices=[('MT', 'Mid-Term'), ('FN', 'Final'), ('OT', 'Other')], max_length=2)),
            ],
        ),
    ]
