# Generated by Django 5.2.5 on 2026-09-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_create_subject', '0001_initial'),
        ('academic_mm_class_and_section', '0001_initial'),
        ('exam_mm_exam_setup', '0003_remove_examsetup_exam_time'),
        ('exam_mm_exmroutine_exmadmit', '0002_alter_examroutine_options_examroutine_end_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamRoutine',
            new_name='ExamsRoutine',
        ),
    ]
