# Generated by Django 5.2.5 on 2025-10-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_exmroutine_exmadmit', '0002_examadmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examadmit',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
