# Generated by Django 5.2.5 on 2026-07-31 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_create_subject', '0002_rename_subject_subject_name'),
        ('exam_mm_exmroutine_exmadmit', '0003_alter_examadmit_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examadmit',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examsadmit', to='academic_create_subject.subject_name'),
        ),
    ]
