# Generated by Django 5.2.5 on 2026-04-25 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_type', models.CharField(choices=[('PTA', 'PTA Committee'), ('MMC', 'MMC Committee'), ('Cabinet', 'Cabinet Committee')], max_length=50)),
                ('recipients', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('Meeting Reminder', 'Meeting Reminder'), ('Meeting Cancellation', 'Meeting Cancellation'), ('General Announcement', 'General Announcement')], max_length=50)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_type', models.CharField(choices=[('PTA', 'PTA Committee'), ('MMC', 'MMC Committee'), ('Cabinet', 'Cabinet Committee')], max_length=50)),
                ('session_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('agenda_items', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='committee/notices/')),
                ('include_member_list', models.BooleanField(default=True)),
                ('status', models.CharField(default='Sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('admin', 'Admin')], default='staff', max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('joining_date', models.DateField()),
                ('qualification', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_school_address', models.TextField(blank=True)),
                ('previous_school_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('pickup_point', models.CharField(blank=True, max_length=100)),
                ('hostel_name', models.CharField(blank=True, max_length=100)),
                ('room_no', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50)),
                ('languages_known', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='staff/resumes/')),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='staff/joining_letters/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_type', models.CharField(max_length=50)),
                ('work_shift', models.CharField(max_length=50)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pension_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='Direct Deposit', max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=100)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.leavetype')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leaves', to='staff.staffprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='staff.staffprofile')),
                ('substitute_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_tasks', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('committee_type', models.CharField(choices=[('PTA', 'PTA Committee'), ('MMC', 'MMC Committee'), ('Cabinet', 'Cabinet Committee')], max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='staff/work_assignments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allocated', models.PositiveIntegerField(default=0)),
                ('used', models.PositiveIntegerField(default=0)),
                ('academic_year', models.CharField(max_length=20)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.leavetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='staff.staffprofile')),
            ],
            options={
                'unique_together': {('staff', 'leave_type', 'academic_year')},
            },
        ),
    ]
