# Generated by Django 5.2.5 on 2026-02-24 20:46

import communication_center_general_notice.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notice_type', models.CharField(choices=[('general', 'General'), ('co_education', 'Co-education')], max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All'), ('students', 'All Students'), ('staff', 'Students & Staff'), ('parents', 'Parents')], default='all', max_length=100)),
                ('priority', models.CharField(choices=[('new', 'New'), ('important', 'Important'), ('info', 'Info')], default='info', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/', validators=[communication_center_general_notice.models.validate_file_size])),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
