# Generated by Django 5.2.5 on 2026-02-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication_center_general_notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='communication_center_notice',
        ),
    ]
