# Generated by Django 5.2.5 on 2026-02-25 20:39

import communication_center_general_notice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_center_general_notice', '0002_rename_notice_communication_center_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('addressed_to', models.CharField(max_length=255)),
                ('organization_branch', models.CharField(max_length=255)),
                ('letter_content', models.TextField()),
                ('letter_type', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='letters/', validators=[communication_center_general_notice.models.validate_file_size])),
                ('issue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
