# Generated by Django 5.2.5 on 2025-09-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
