# Generated by Django 5.2.5 on 2025-09-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_subject_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('term', 'Term Exam'), ('assessment', 'Assessment'), ('other', 'Other')], max_length=20)),
                ('academic_year', models.PositiveIntegerField(help_text='e.g., 2025')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('class_selection', models.CharField(help_text='e.g., Class 10', max_length=100)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('evening', 'Evening')], max_length=20)),
                ('stream', models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], help_text='Optional stream scope for this routine', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, help_text='Optional, will often be derived from date', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=200)),
                ('exam_hall', models.CharField(blank=True, max_length=100)),
                ('stream', models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=20, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exam.examroutine')),
            ],
            options={
                'verbose_name': 'Exam Routine Item',
                'verbose_name_plural': 'Exam Routine Items',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
