# Generated by Django 5.2.5 on 2025-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stipend_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=50)),
                ('stipend_type', models.CharField(choices=[('Merit', 'Merit-Based'), ('Special', 'Special Categories'), ('Financial', 'Financial Aid'), ('Sports', 'Sports Scholarship')], max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
