# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stipend_free_hf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('concession_type', models.CharField(choices=[('full free', 'Full Free'), ('half free', 'Half Free')], max_length=50)),
                ('category', models.CharField(choices=[('low income', 'Low Income'), ('meritorious', 'Meritorious'), ('special cases', 'Special Cases'), ('staff children', 'Staff Children')], max_length=50)),
                ('valid_till', models.DateField()),
                ('original_fee', models.CharField(max_length=100)),
                ('concession_ammount', models.CharField(max_length=100)),
                ('reason_for_concession', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], max_length=50)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.academicclass')),
            ],
        ),
        migrations.CreateModel(
            name='stipend_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('stipend_type', models.CharField(choices=[('Merit', 'Merit-Based'), ('Special', 'Special Categories'), ('Financial', 'Financial Aid'), ('Sports', 'Sports Scholarship')], max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.academicclass')),
            ],
        ),
    ]
