# Generated by Django 5.2.5 on 2026-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_std_stipent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipend_free_hf',
            name='concession_type',
            field=models.CharField(choices=[('full free', 'Full Free'), ('half free', 'Half Free'), ('quarter free', 'Quarter Free'), ('special free', 'Special Free'), ('hsp', 'HSP'), ('staff children', 'Staff Children'), ('scholarship', 'Scholarship')], max_length=50),
        ),
    ]
