# Generated by Django 5.2.5 on 2025-11-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_std_stipent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stipend_free_hf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=50)),
                ('concession_type', models.CharField(choices=[('full free', 'Full Free'), ('half free', 'Half Free')], max_length=50)),
                ('category', models.CharField(choices=[('low income', 'Low Income'), ('meritorious', 'Meritorious'), ('special cases', 'Special Cases'), ('staff children', 'Staff Children')], max_length=50)),
                ('valid_till', models.DateField()),
                ('original_fee', models.CharField(max_length=100)),
                ('concession_ammount', models.CharField(max_length=100)),
                ('reason_for_concession', models.TextField()),
            ],
        ),
    ]
