# Generated by Django 5.2.5 on 2025-11-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_std_stipent', '0002_stipend_free_hf'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipend_free_hf',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=50),
            preserve_default=False,
        ),
    ]
