# Generated by Django 5.2.5 on 2026-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('student_name_bn', models.CharField(max_length=255)),
                ('father_name_bn', models.CharField(max_length=255)),
                ('mother_name_bn', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=100)),
                ('upazila', models.CharField(default='ব্রাহ্মণবাড়িয়া সদর', max_length=100)),
                ('district', models.CharField(default='ব্রাহ্মণবাড়িয়া', max_length=100)),
                ('leaving_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('age_years', models.CharField(max_length=10)),
                ('age_months', models.CharField(max_length=10)),
                ('age_days', models.CharField(max_length=10)),
                ('current_class', models.CharField(max_length=100)),
                ('promoted_from_class', models.CharField(max_length=100)),
                ('promoted_to_class', models.CharField(max_length=100)),
                ('is_promoted', models.BooleanField(default=True)),
                ('fees_paid_up_to_year', models.CharField(max_length=10)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('leaving_reason', models.CharField(choices=[('অভিভাবকের অভিপ্রায়', 'অভিভাবকের অভিপ্রায়'), ('বাসস্থান পরিবর্তন', 'বাসস্থান পরিবর্তন'), ('শারীরিক অসুস্থতা', 'শারীরিক অসুস্থতা'), ('অন্যান্য', 'অন্যান্য')], default='অভিভাবকের অভিপ্রায়', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
