# Generated by Django 5.2.5 on 2026-09-13 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_teacher_duty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examduty',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examduty',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='examduty',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examduty',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
