# Generated by Django 5.2.5 on 2026-09-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_teacher_duty', '0002_remove_examduty_subject_remove_examduty_time_slot_and_more'),
        ('teacher_mm_teacher', '0008_alter_teacherandstaffprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examduty',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'employee_type__in': ['head_teacher', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_duties', to='teacher_mm_teacher.teacherandstaffprofile'),
        ),
    ]
