# Generated by Django 5.2.5 on 2025-11-30 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='pan_or_id_number',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='casual_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('part_time', 'Part Time')], max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='epf_no',
            field=models.CharField(blank=True, help_text='Employee Provident Fund number', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hostel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='joining_letter',
            field=models.FileField(blank=True, null=True, upload_to='teachers/joining_letter/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='maternity_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='medical_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN or Tax ID number', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='teachers/resume/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='room_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='route_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sick_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account for authentication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('full_day', 'Full Day')], max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='languages_known',
            field=models.JSONField(blank=True, default=list, help_text='List of languages known'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='previous_school_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(help_text='Unique teacher identifier', max_length=50, unique=True),
        ),
    ]
