# Generated by Django 5.2.5 on 2026-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_section',
            field=models.CharField(max_length=256),
        ),
    ]
