# Generated by Django 5.2.5 on 2026-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='roll_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
