# Generated by Django 5.2.5 on 2026-07-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_academic_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='class_section',
            new_name='classname',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
