# Generated by Django 5.2.5 on 2026-05-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('plaintiff', models.CharField(max_length=255)),
                ('defendant', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('date_filed', models.DateField()),
                ('progress_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('pending', 'Pending'), ('closed', 'Closed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_filed'],
            },
        ),
    ]
