# Generated by Django 5.2.5 on 2026-08-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_bn', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('father_name_bn', models.CharField(max_length=255)),
                ('mother_name_bn', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=10)),
                ('academic_year', models.CharField(default='2018-2019', max_length=50)),
                ('exam_month', models.CharField(choices=[('জানুয়ারি', 'জানুয়ারি'), ('ফেব্রুয়ারি', 'ফেব্রুয়ারি'), ('মার্চ', 'মার্চ'), ('এপ্রিল', 'এপ্রিল'), ('মে', 'মে'), ('জুন', 'জুন'), ('জুলাই', 'জুলাই'), ('আগস্ট', 'আগস্ট'), ('সেপ্টেম্বর', 'সেপ্টেম্বর'), ('অক্টোবর', 'অক্টোবর'), ('নভেম্বর', 'নভেম্বর'), ('ডিসেম্বর', 'ডিসেম্বর')], max_length=50)),
                ('board', models.CharField(choices=[('মাধ্যমিক ও উচ্চ মাধ্যমিক শিক্ষা বোর্ড, রাজশাহী', 'মাধ্যমিক ও উচ্চ মাধ্যমিক শিক্ষা বোর্ড, রাজশাহী'), ('বাংলাদেশ কারিগরি শিক্ষা বোর্ড', 'বাংলাদেশ কারিগরি শিক্ষা বোর্ড')], max_length=100)),
                ('department', models.CharField(choices=[('মানবিক', 'মানবিক'), ('বিজ্ঞান', 'বিজ্ঞান'), ('এপারেল ম্যানুফেকচারিং বেসিকস', 'এপারেল ম্যানুফেকচারিং বেসিকস'), ('ফুড প্রসেসিং এন্ড প্রিজার্ভেশন', 'ফুড প্রসেসিং এন্ড প্রিজার্ভেশন'), ('ব্যবসায় শিক্ষা', 'ব্যবসায় শিক্ষা')], max_length=100)),
                ('GPA', models.CharField(max_length=10)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A+', max_length=10)),
                ('roll', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
