# Generated by Django 5.2.5 on 2026-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_bn', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('father_name_bn', models.CharField(max_length=255)),
                ('mother_name_bn', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('passing_year', models.IntegerField()),
                ('exam_month', models.CharField(max_length=20)),
                ('board', models.CharField(choices=[('Rajshahi Education Board', 'Rajshahi Education Board'), ('Technical Education Board', 'Technical Education Board')], max_length=100)),
                ('department', models.CharField(choices=[('Humanities', 'Humanities'), ('Science', 'Science'), ('Apparel Manufacturing Basics', 'Apparel Manufacturing Basics'), ('Food Processing and Preservation', 'Food Processing and Preservation')], max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('roll', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
