# Generated by Django 5.2.5 on 2026-08-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_mm_testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='board',
            field=models.CharField(choices=[('রাজশাহী শিক্ষাবোর্ড', 'রাজশাহী শিক্ষাবোর্ড'), ('কারিগরি শিক্ষাবোর্ড', 'কারিগরি শিক্ষাবোর্ড')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='department',
            field=models.CharField(choices=[('মানবিক', 'মানবিক'), ('বিজ্ঞান', 'বিজ্ঞান'), ('এপারেল ম্যানুফেকচারিং বেসিকস', 'এপারেল ম্যানুফেকচারিং বেসিকস'), ('ফুড প্রসেসিং এন্ড প্রিজার্ভেশন', 'ফুড প্রসেসিং এন্ড প্রিজার্ভেশন')], max_length=100),
        ),
    ]
