# Generated by Django 5.2.5 on 2026-08-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_mm_testimonial', '0002_alter_studentapplication_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='exam_month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='gpa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='passing_year',
            field=models.CharField(max_length=10),
        ),
    ]
