# Generated by Django 5.2.5 on 2026-08-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_mm_testimonial', '0003_alter_studentapplication_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='academic_year',
            field=models.CharField(default='২০১৮-২০১৯', max_length=50),
        ),
    ]
