# Generated by Django 5.2.5 on 2026-08-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_mm_testimonial', '0004_studentapplication_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='grade',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='academic_year',
            field=models.CharField(default='2018-2019', max_length=50),
        ),
    ]
