# Generated by Django 5.2.5 on 2026-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_mm_testimonial', '0005_studentapplication_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='board',
            field=models.CharField(choices=[('মাধ্যমিক ও উচ্চ মাধ্যমিক শিক্ষা বোর্ড, রাজশাহী', 'মাধ্যমিক ও উচ্চ মাধ্যমিক শিক্ষা বোর্ড, রাজশাহী'), ('বাংলাদেশ কারিগরি শিক্ষা বোর্ড', 'বাংলাদেশ কারিগরি শিক্ষা বোর্ড')], max_length=100),
        ),
    ]
