# Generated by Django 5.2.5 on 2026-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_mm_testimonial', '0006_alter_studentapplication_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='gpa',
            new_name='GPA',
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='exam_month',
            field=models.CharField(choices=[('জানুয়ারি', 'জানুয়ারি'), ('ফেব্রুয়ারি', 'ফেব্রুয়ারি'), ('মার্চ', 'মার্চ'), ('এপ্রিল', 'এপ্রিল'), ('মে', 'মে'), ('জুন', 'জুন'), ('জুলাই', 'জুলাই'), ('আগস্ট', 'আগস্ট'), ('সেপ্টেম্বর', 'সেপ্টেম্বর'), ('অক্টোবর', 'অক্টোবর'), ('নভেম্বর', 'নভেম্বর'), ('ডিসেম্বর', 'ডিসেম্বর')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A+', max_length=10),
        ),
    ]
