# Generated by Django 5.2.5 on 2026-08-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_mm_testimonial', '0007_rename_gpa_studentapplication_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='department',
            field=models.CharField(choices=[('মানবিক', 'মানবিক'), ('বিজ্ঞান', 'বিজ্ঞান'), ('এপারেল ম্যানুফেকচারিং বেসিকস', 'এপারেল ম্যানুফেকচারিং বেসিকস'), ('ফুড প্রসেসিং এন্ড প্রিজার্ভেশন', 'ফুড প্রসেসিং এন্ড প্রিজার্ভেশন'), ('ব্যবসায় শিক্ষা', 'ব্যবসায় শিক্ষা')], max_length=100),
        ),
    ]
