# Generated by Django 5.2.5 on 2025-10-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_exam_setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='exm_mm_exam_setup',
        ),
    ]
