# Generated by Django 5.2.5 on 2026-09-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
        ('exam_mm_exam_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day')], max_length=10)),
                ('exam_time', models.TimeField(help_text='Format: HH:MM:SS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setups', to='academic_mm_class_and_section.academicclass')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setups', to='exam_mm_exam_setup.examname')),
                ('sections', models.ManyToManyField(related_name='exam_setups', to='academic_mm_class_and_section.section')),
            ],
        ),
        migrations.DeleteModel(
            name='exm_mm_exam_setup',
        ),
    ]
