# Generated by Django 5.2.5 on 2026-09-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_exam_setup', '0002_examname_examsetup_delete_exm_mm_exam_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsetup',
            name='exam_time',
        ),
    ]
