# Generated by Django 5.2.5 on 2026-07-31 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_create_subject', '0002_rename_subject_subject_name'),
        ('exam_mm_exam_setup', '0002_rename_exam_exm_mm_exam_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exm_mm_exam_setup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic_create_subject.subject_name'),
        ),
    ]
