# Generated by Django 5.2.5 on 2026-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=255)),
                ('training_name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('date_to', models.DateField()),
                ('total_days', models.IntegerField()),
                ('authority', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
