# Generated by Django 5.2.5 on 2026-05-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_collect_fee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='amount',
        ),
    ]
