# Generated by Django 5.2.5 on 2026-05-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_collect_fee', '0003_feecollection_discount_amount_and_more'),
        ('account_mm_create_fee', '0009_formfilupamount_assignment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='fee',
        ),
        migrations.CreateModel(
            name='FeeCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account_mm_collect_fee.feecollection')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_mm_create_fee.createfee')),
            ],
        ),
    ]
