# Generated by Django 5.2.5 on 2026-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('expense_category', models.CharField(choices=[('Facilities', 'Facilities & Maintenance'), ('Academic', 'Academic Resources'), ('Salary', 'Staff Salaries'), ('Transport', 'Transportation'), ('Tech', 'Technology'), ('Others', 'Others')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
