# Generated by Django 5.2.5 on 2025-12-07 21:48

import django.core.validators
import teacher_mm_workdistribute.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_workdistribute', '0003_workassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='work_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), teacher_mm_workdistribute.models.validate_file_size]),
        ),
    ]
