# Generated by Django 5.2.5 on 2026-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
