# Generated by Django 5.2.5 on 2026-02-16 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('achievement', models.CharField(max_length=255)),
                ('roll', models.PositiveIntegerField()),
                ('student_class', models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], default='class 10', max_length=10)),
                ('section', models.CharField(choices=[('section A', 'Section A'), ('section B', 'Section B'), ('section C', 'Section C'), ('section D', 'Section D')], default='section A', max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, help_text='Upload a later (JPG or PNG, Max 1MB)', null=True, upload_to='student_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Later Picture (1080x1080)')),
            ],
        ),
    ]
