# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('achievement', models.CharField(max_length=255)),
                ('roll', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('photo', models.ImageField(help_text='Upload a later (JPG or PNG, Max 1MB)', upload_to='student_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Later Picture (1080x1080)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.section')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.academicclass')),
            ],
        ),
    ]
