# Generated by Django 5.2.5 on 2026-02-21 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mm_top_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_student',
            name='photo',
            field=models.ImageField(default='', help_text='Upload a later (JPG or PNG, Max 1MB)', upload_to='student_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Later Picture (1080x1080)'),
            preserve_default=False,
        ),
    ]
