# Generated by Django 5.2.5 on 2025-12-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice Chairperson', 'Vice Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member')], max_length=50)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
