# Generated by Django 5.2.5 on 2025-12-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_comitee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='member_avatars/'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='committee_type',
            field=models.CharField(choices=[('PTA', 'PTA Committee'), ('MMC', 'MMC Committee'), ('CABINET', 'Cabinet Committee')], default='PTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='position',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Member', 'Member')], max_length=50),
        ),
    ]
