# Generated by Django 5.2.5 on 2025-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name_local', models.CharField(max_length=255)),
                ('eiin', models.CharField(max_length=10, unique=True)),
                ('institute_type', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Madrasa', 'Madrasa')], max_length=50)),
                ('education_board_code', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('emis_code', models.CharField(max_length=20)),
                ('mpo_code', models.CharField(blank=True, max_length=20)),
                ('technical_mpo_code', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHITTAGONG', 'Chittagong'), ('RAJSHAHI', 'Rajshahi'), ('KHULNA', 'Khulna'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('RANGPUR', 'Rangpur'), ('MYMENSINGH', 'Mymensingh')], max_length=50)),
                ('parliamentary_constituency', models.CharField(blank=True, max_length=100)),
                ('sub_district_thana', models.CharField(max_length=100)),
                ('village_road_area', models.CharField(max_length=255)),
                ('union', models.CharField(blank=True, max_length=100)),
                ('mouza_mahalla_name', models.CharField(blank=True, max_length=255)),
                ('mouza_mahalla_number', models.CharField(blank=True, max_length=50)),
                ('post_office', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('institute_phone', models.CharField(blank=True, max_length=20)),
                ('institute_mobile', models.CharField(max_length=20)),
                ('institute_fax', models.CharField(blank=True, max_length=20)),
                ('institute_email', models.EmailField(max_length=254)),
                ('website_address', models.URLField(blank=True)),
                ('head_of_institute', models.CharField(max_length=255)),
                ('head_mobile', models.CharField(max_length=20)),
                ('institute_name_eng', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
