# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name_local', models.CharField(max_length=255)),
                ('eiin', models.CharField(max_length=10, unique=True)),
                ('institute_type', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Madrasa', 'Madrasa')], max_length=50)),
                ('education_board_code', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('emis_code', models.CharField(max_length=20)),
                ('mpo_code', models.CharField(blank=True, max_length=20)),
                ('technical_mpo_code', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHITTAGONG', 'Chittagong'), ('RAJSHAHI', 'Rajshahi'), ('KHULNA', 'Khulna'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('RANGPUR', 'Rangpur'), ('MYMENSINGH', 'Mymensingh')], max_length=50)),
                ('parliamentary_constituency', models.CharField(blank=True, max_length=100)),
                ('sub_district_thana', models.CharField(max_length=100)),
                ('village_road_area', models.CharField(max_length=255)),
                ('union', models.CharField(blank=True, max_length=100)),
                ('mouza_mahalla_name', models.CharField(blank=True, max_length=255)),
                ('mouza_mahalla_number', models.CharField(blank=True, max_length=50)),
                ('post_office', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('institute_phone', models.CharField(blank=True, max_length=20)),
                ('institute_mobile', models.CharField(max_length=20)),
                ('institute_fax', models.CharField(blank=True, max_length=20)),
                ('institute_email', models.EmailField(max_length=254)),
                ('website_address', models.URLField(blank=True)),
                ('head_of_institute', models.CharField(max_length=255)),
                ('head_mobile', models.CharField(max_length=20)),
                ('institute_name_eng', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalization_date', models.DateField(blank=True, null=True)),
                ('administrative_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_unit_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geographic_location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_in_enclave', models.CharField(default='No', max_length=10)),
                ('any_case_in_institute', models.CharField(default='No', max_length=10)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='institute_mm_institute_profile.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteInfoBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Branch')),
                ('routing_number', models.CharField(max_length=20, verbose_name='Routing Number')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=50, verbose_name='Type of Account')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('purpose_of_account', models.TextField(blank=True, null=True, verbose_name='Purpose of Account')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='institute_mm_institute_profile.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_establishment', models.DateField()),
                ('subjects', models.JSONField(default=list)),
                ('academic_levels', models.JSONField(default=list)),
                ('groups', models.JSONField(default=list)),
                ('medium', models.CharField(choices=[('BN', 'Bangla'), ('EN', 'English'), ('UM', 'Urdu')], max_length=10)),
                ('for_whom', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Co-Educational(Combined)', 'Co-Educational(Combined)')], max_length=50)),
                ('management_type', models.CharField(blank=True, max_length=100)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('recognition', models.CharField(choices=[('Recognized', 'Recognized (স্বীকৃত)'), ('Non-Govt', 'Non-Govt (বেসরকারী)')], max_length=50)),
                ('approval_level', models.CharField(blank=True, max_length=100)),
                ('max_permitted_level', models.CharField(blank=True, max_length=100)),
                ('date_of_first_recognition', models.DateField(blank=True, null=True)),
                ('expiry_date_of_recognition', models.DateField(blank=True, null=True)),
                ('institution_mpo_enlistment', models.BooleanField(default=False)),
                ('mpo_level', models.CharField(blank=True, max_length=50)),
                ('date_of_mpo_enlistment', models.DateField(blank=True, null=True)),
                ('mpo_code', models.CharField(blank=True, max_length=50)),
                ('mpo_evidence_technical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='institute_mm_institute_profile.institution')),
            ],
        ),
    ]
