# Generated by Django 5.2.5 on 2025-12-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_institute_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_establishment', models.DateField()),
                ('subjects', models.JSONField(default=list)),
                ('academic_levels', models.JSONField(default=list)),
                ('groups', models.JSONField(default=list)),
                ('medium', models.CharField(choices=[('BN', 'Bangla'), ('EN', 'English'), ('UM', 'Urdu')], max_length=10)),
                ('for_whom', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Co-Educational(Combined)', 'Co-Educational(Combined)')], max_length=50)),
                ('management_type', models.CharField(blank=True, max_length=100)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('recognition', models.CharField(choices=[('Recognized', 'Recognized (স্বীকৃত)'), ('Non-Govt', 'Non-Govt (বেসরকারী)')], max_length=50)),
                ('approval_level', models.CharField(blank=True, max_length=100)),
                ('max_permitted_level', models.CharField(blank=True, max_length=100)),
                ('date_of_first_recognition', models.DateField(blank=True, null=True)),
                ('expiry_date_of_recognition', models.DateField(blank=True, null=True)),
                ('institution_mpo_enlistment', models.BooleanField(default=False)),
                ('mpo_level', models.CharField(blank=True, max_length=50)),
                ('date_of_mpo_enlistment', models.DateField(blank=True, null=True)),
                ('mpo_code', models.CharField(blank=True, max_length=50)),
                ('mpo_evidence_technical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
