# Generated by Django 5.2.5 on 2026-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_institute_profile', '0002_institutiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteInfoBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Branch')),
                ('routing_number', models.CharField(max_length=20, verbose_name='Routing Number')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=50, verbose_name='Type of Account')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('purpose_of_account', models.TextField(blank=True, null=True, verbose_name='Purpose of Account')),
            ],
        ),
    ]
