# Generated by Django 5.2.5 on 2026-01-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_institute_profile', '0003_instituteinfobank'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalization_date', models.DateField(blank=True, null=True)),
                ('administrative_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_unit_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geographic_location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_in_enclave', models.CharField(default='No', max_length=10)),
                ('any_case_in_institute', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
