# Generated by Django 5.2.5 on 2026-01-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_institute_profile', '0004_instituteothers'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteinfobank',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='institute_mm_institute_profile.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituteothers',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='institute_mm_institute_profile.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutiondetails',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='institute_mm_institute_profile.institution'),
            preserve_default=False,
        ),
    ]
