# Generated by Django 5.2.5 on 2026-09-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('student_name_bn', models.CharField(max_length=255)),
                ('father_name_bn', models.CharField(max_length=255)),
                ('mother_name_bn', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=100)),
                ('upazila', models.CharField(default='নবীনগর', max_length=100)),
                ('district', models.CharField(default='ব্রাহ্মণবাড়িয়া', max_length=100)),
                ('school_name_bn', models.CharField(default='অত্র বিদ্যালয়', max_length=255)),
                ('academic_year', models.CharField(help_text='যেমন: ২০০৩/২০২৩', max_length=20)),
                ('admission_date', models.DateField()),
                ('admission_class', models.CharField(default='ষষ্ঠ', max_length=100)),
                ('passing_year', models.CharField(help_text='যেমন: ২০০৮/২০২৪', max_length=10)),
                ('exam_group', models.CharField(choices=[('বিজ্ঞান', 'বিজ্ঞান'), ('মানবিক', 'মানবিক'), ('ব্যবসায় শিক্ষা', 'ব্যবসায় শিক্ষা'), ('সাধারণ', 'সাধারণ')], default='বিজ্ঞান', max_length=50)),
                ('gpa', models.CharField(help_text='যেমন: ৪.৬৯', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
