# Generated by Django 5.2.5 on 2026-06-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_create_subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Subject_Name',
        ),
    ]
