# Generated by Django 5.2.5 on 2026-08-21 22:45

import apps.students.models.core
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=32)),
                ('admission_number', models.CharField(max_length=64)),
                ('admission_date', models.DateField()),
                ('roll_number', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('alumni', 'Alumni'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name_bn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (Bangla)')),
                ('class_name_static', models.CharField(blank=True, db_column='class_name', max_length=64, null=True)),
                ('section_static', models.CharField(blank=True, db_column='section', max_length=32, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\d{17}$', message='Enter a valid 17-digit birth certificate number.')], verbose_name='Birth Certificate Number')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('house', models.CharField(blank=True, max_length=64, null=True)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('hindu', 'Hindu'), ('christian', 'Christian'), ('buddhism', 'Buddhism'), ('others', 'Others')], max_length=64, null=True)),
                ('category', models.CharField(blank=True, choices=[('general', 'General'), ('vocational', 'Vocational')], max_length=16, null=True)),
                ('primary_contact_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Enter a valid phone number with country code if applicable.')])),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('caste', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=64, null=True)),
                ('scholarship', models.CharField(blank=True, choices=[('hsp', 'HSP'), ('dte', 'DTE'), ('general scholarship', 'General Scholarship'), ('talentpul scholarship', 'Talentpul Scholarship'), ('hf', 'HF'), ('f', 'F')], max_length=25, null=True)),
                ('student_id_card_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('is_id_card_generated', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, help_text='Upload a profile photo (JPG or PNG, Max 1MB)', null=True, upload_to=apps.students.models.core.student_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student_profile_studentpersonalinfo',
                'unique_together': {('academic_year', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='GuardianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_photo', models.ImageField(blank=True, null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('father_name', models.CharField(max_length=100)),
                ('father_name_bn', models.CharField(blank=True, max_length=150, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_nid_or_birth_certificate', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_photo', models.ImageField(blank=True, null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_name_bn', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_nid_or_birth_certificate', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_type', models.CharField(choices=[('Parent', 'Parent'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Parent', max_length=20)),
                ('guardian_photo', models.ImageField(blank=True, null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name_bn', models.CharField(blank=True, max_length=150, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_address', models.TextField(blank=True, null=True)),
                ('sibling_studying_same_school', models.BooleanField(default=False)),
                ('sibling_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sibling_admission_no', models.CharField(blank=True, max_length=50, null=True)),
                ('present_address_village', models.CharField(max_length=255)),
                ('present_address_post_office', models.CharField(max_length=255)),
                ('present_address_sub_district', models.CharField(max_length=255)),
                ('present_address_district', models.CharField(max_length=255)),
                ('permanent_address_village', models.CharField(max_length=255)),
                ('permanent_address_post_office', models.CharField(max_length=255)),
                ('permanent_address_sub_district', models.CharField(max_length=255)),
                ('permanent_address_district', models.CharField(max_length=255)),
                ('student', models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='guardian_info', to='students.student')),
            ],
            options={
                'db_table': 'student_profile_studentgurdianinfo',
            },
        ),
        migrations.CreateModel(
            name='AdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_point', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='documents/medical/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='documents/transfer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('medical_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Other', 'Other')], max_length=10, null=True)),
                ('Disease', models.CharField(blank=True, max_length=100, null=True)),
                ('medication', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('previous_school_address', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('admission_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('sports', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='students.student')),
            ],
            options={
                'db_table': 'student_profile_studentadditionalinfo',
            },
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_taken', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low (Warning)'), ('medium', 'Medium (Suspension)'), ('high', 'High (Expulsion)')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='students.student')),
            ],
            options={
                'db_table': 'student_discipline_records',
                'ordering': ['-incident_date'],
            },
        ),
    ]
