# Generated by Django 5.2.5 on 2026-08-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_mm_class_and_section.academicclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_mm_class_and_section.section'),
        ),
    ]
