# Generated by Django 5.2.5 on 2026-04-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_id_card_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id_card_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_taken', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low (Warning)'), ('medium', 'Medium (Suspension)'), ('high', 'High (Expulsion)')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='students.student')),
            ],
            options={
                'db_table': 'student_discipline_records',
                'ordering': ['-incident_date'],
            },
        ),
    ]
