# Generated by Django 5.2.5 on 2026-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_id_card_generated_student_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardiandetails',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='guardian_name_bn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
