# Generated by Django 5.2.5 on 2026-09-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_class_name_static_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.CharField(blank=True, choices=[('hsp', 'HSP'), ('dte', 'DTE'), ('general scholarship', 'General Scholarship'), ('talentpul scholarship', 'Talentpul Scholarship'), ('hf', 'HF'), ('f', 'F'), ('non', 'Non')], max_length=25, null=True),
        ),
    ]
