# Generated by Django 5.2.5 on 2026-08-20 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_guardiandetails_father_name_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\d{17}$', message='Enter a valid 17-digit birth certificate number.')], verbose_name='Birth Certificate Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (Bangla)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.CharField(blank=True, choices=[('hsp', 'HSP'), ('dte', 'DTE'), ('general scholarship', 'General Scholarship'), ('talentpul scholarship', 'Talentpul Scholarship'), ('hf', 'HF'), ('f', 'F')], max_length=25, null=True),
        ),
    ]
