# Generated by Django 5.2.5 on 2026-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_birth_certificate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardiandetails',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='guardiandetails',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='permanent_address_district',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='permanent_address_post_office',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='permanent_address_sub_district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='permanent_address_village',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='present_address_district',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='present_address_post_office',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='present_address_sub_district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='present_address_village',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
