# Generated by Django 5.2.5 on 2026-01-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mm_book_distribution', '0002_letterdistribution'),
        ('student_profile', '0002_alter_studentadditionalinfo_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterdistribution',
            name='student_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='student_profile.studentpersonalinfo'),
            preserve_default=False,
        ),
    ]
