# Generated by Django 5.2.5 on 2026-06-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_class_routine', '0002_alter_classroutine_teacher_teacher'),
        ('academic_create_subject', '0002_rename_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_create_subject.subject_name'),
        ),
    ]
