# Generated by Django 5.2.5 on 2026-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_class_routine', '0003_alter_classroutine_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='section',
            field=models.CharField(choices=[('Section A', 'Section A'), ('Section B', 'Section B'), ('Section C', 'Section C'), ('Section D', 'Section D')], max_length=10),
        ),
    ]
