# Generated by Django 5.2.5 on 2025-09-06 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile photo (JPG or PNG, Max 1MB)', null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)'),
        ),
    ]
