# Generated by Django 5.2.5 on 2025-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_admission', '0002_alter_studentadmission_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='family_annual_income',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='father_name_bn',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='father_name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='father_nid_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='guardian_profession',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='mother_name_bn',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='mother_name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='mother_nid_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='permanent_address_district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='permanent_address_post_office',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='permanent_address_sub_district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='permanent_address_village',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='present_address_district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='present_address_post_office',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='present_address_sub_district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='present_address_village',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='sibling_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
