# Generated by Django 5.2.5 on 2025-11-30 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_add_user_link_and_extended_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_days', models.PositiveIntegerField(default=0, help_text='Default number of days allocated for this leave type per year')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(help_text='Date when leave was applied')),
                ('from_date', models.DateField(help_text='Leave start date')),
                ('to_date', models.DateField(help_text='Leave end date')),
                ('leave_days', models.CharField(choices=[('full_day', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full_day', help_text='Type of leave day', max_length=20)),
                ('no_of_days', models.DecimalField(decimal_places=1, help_text='Total number of leave days', max_digits=5)),
                ('reason', models.TextField(blank=True, help_text='Reason for taking leave')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, help_text='Remarks by admin when approving/declining')),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='teacher_leave.leavetype')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Leave',
                'verbose_name_plural': 'Teacher Leaves',
                'ordering': ['-applied_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allocated', models.PositiveIntegerField(default=0, help_text='Total leaves allocated for the year')),
                ('used', models.PositiveIntegerField(default=0, help_text='Total leaves used')),
                ('year', models.PositiveIntegerField(help_text='Year for which this balance applies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='teacher.teacher')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='teacher_leave.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'ordering': ['-year', 'leave_type__name'],
                'unique_together': {('teacher', 'leave_type', 'year')},
            },
        ),
    ]
