# Generated by Django 5.2.5 on 2026-08-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityFurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('educational_tools', 'Educational_tools'), ('storage', 'Strorage'), ('sports_equipment', 'Sports_Equipment')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('condition_status', models.CharField(choices=[('good', 'Good'), ('needs repair', 'Needs Repair'), ('replace', 'Replace')], max_length=50)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
