# Generated by Django 5.2.5 on 2026-01-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityFurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('chair', 'Chair'), ('table', 'Table'), ('desk', 'Desk'), ('benches', 'Benches')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('condition_status', models.CharField(choices=[('good', 'Good'), ('needs repair', 'Needs Repair'), ('replace', 'Replace')], max_length=50)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
