# Generated by Django 5.2.5 on 2026-08-30 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_facilities', '0001_initial'),
        ('reg_mm_stock_event', '0002_alter_stockinventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityfurnitureitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='facilityfurnitureitem',
            name='item_type',
        ),
        migrations.AddField(
            model_name='facilityfurnitureitem',
            name='stock_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facility_allocations', to='reg_mm_stock_event.stockinventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilityfurnitureitem',
            name='condition_status',
            field=models.CharField(choices=[('good', 'Good'), ('needs repair', 'Needs Repair'), ('replace', 'Replace')], default='good', max_length=50),
        ),
    ]
