# Generated by Django 5.2.5 on 2026-01-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityfurnitureitem',
            name='item_type',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('educational_tools', 'Educational_tools'), ('storage', 'Strorage'), ('sports_equipment', 'Sports_Equipment')], max_length=50),
        ),
    ]
