# Generated by Django 5.2.5 on 2026-08-30 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_facilities', '0002_remove_facilityfurnitureitem_item_name_and_more'),
        ('reg_mm_stock_event', '0002_alter_stockinventory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='facilityfurnitureitem',
            name='condition_status',
            field=models.CharField(choices=[('needs_repair', 'Needs Repair'), ('replace', 'Replace')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facilityfurnitureitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_issues', to='reg_mm_stock_event.stockinventory'),
        ),
        migrations.AlterField(
            model_name='facilityfurnitureitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_items', to='institute_mm_facilities.facilitylocation'),
        ),
    ]
