# Generated by Django 5.2.5 on 2026-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_facilities', '0003_facilitylocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityfurnitureitem',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
