# Generated by Django 5.2.5 on 2026-08-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0002_remove_teacher_teacher_id_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
