# Generated by Django 5.2.5 on 2026-08-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
        ('teacher_mm_teacher', '0002_teacherss'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nid_card_copy',
            field=models.FileField(blank=True, null=True, upload_to='teachers/nid_cards/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nid_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_order_copy',
            field=models.FileField(blank=True, null=True, upload_to='teachers/office_orders/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academic_mm_class_and_section.academicclass'),
        ),
    ]
