# Generated by Django 5.2.5 on 2026-08-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0003_alter_teacher_facebook_alter_teacher_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
