# Generated by Django 5.2.5 on 2026-08-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0003_teacher_district_teacher_father_name_bn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_assigned',
        ),
    ]
