# Generated by Django 5.2.5 on 2026-08-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0004_alter_teacher_facebook_alter_teacher_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='route_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
