# Generated by Django 5.2.5 on 2026-08-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0004_remove_teacher_class_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
