# Generated by Django 5.2.5 on 2026-09-04 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0005_remove_teacher_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherss',
            name='user',
        ),
        migrations.CreateModel(
            name='TeacherAndStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff')], default='teacher', help_text='Select whether this profile belongs to a Teacher or Staff', max_length=20)),
                ('designation', models.CharField(blank=True, help_text='Designation e.g. Senior Math Teacher, Accountant, Office Assistant', max_length=150)),
                ('department', models.CharField(blank=True, help_text='Department e.g. Science, Accounts, Administration', max_length=150)),
                ('name_bn', models.CharField(blank=True, help_text='বাংলা নাম', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('languages_known', models.JSONField(blank=True, default=list, help_text='List of languages known')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('primary_contact_number', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('father_name_bn', models.CharField(blank=True, help_text='বাবার বাংলা নাম', max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mother_name_bn', models.CharField(blank=True, help_text='মায়ের বাংলা নাম', max_length=150)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('work_experience', models.CharField(blank=True, max_length=255)),
                ('previous_school_name', models.CharField(blank=True, max_length=255)),
                ('previous_school_address', models.CharField(blank=True, max_length=255)),
                ('previous_school_phone', models.CharField(blank=True, max_length=25)),
                ('district', models.CharField(blank=True, help_text='নিজ জেলা', max_length=100)),
                ('permanent_address', models.TextField(blank=True)),
                ('current_address', models.TextField(blank=True)),
                ('nid_number', models.CharField(blank=True, help_text='NID নম্বর', max_length=50)),
                ('pan_number', models.CharField(blank=True, help_text='PAN or Tax ID number', max_length=50)),
                ('epf_no', models.CharField(blank=True, help_text='Employee Provident Fund number', max_length=50)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('part_time', 'Part Time')], max_length=50)),
                ('work_shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('full_day', 'Full Day')], max_length=50)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('medical_leaves', models.PositiveIntegerField(default=0)),
                ('casual_leaves', models.PositiveIntegerField(default=0)),
                ('maternity_leaves', models.PositiveIntegerField(default=0)),
                ('sick_leaves', models.PositiveIntegerField(default=0)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=50)),
                ('route_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_point', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel_id', models.CharField(blank=True, max_length=50)),
                ('room_no', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_staff/photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teacher_staff/resumes/')),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='teacher_staff/joining_letters/')),
                ('office_order_copy', models.FileField(blank=True, null=True, upload_to='teacher_staff/office_orders/')),
                ('nid_card_copy', models.FileField(blank=True, null=True, upload_to='teacher_staff/nid_cards/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account created during Auth', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher & Staff Profile',
                'verbose_name_plural': 'Teacher & Staff Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
