# Generated by Django 5.2.5 on 2026-09-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0006_remove_teacher_user_remove_teacherss_user_and_more'),
        ('teacher_mm_teacher_leave', '0002_alter_leavebalance_teacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Teacherss',
        ),
    ]
