# Generated by Django 5.2.5 on 2026-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0007_delete_teacher_delete_teacherss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherandstaffprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Department e.g. Administration, Science, Accounts', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacherandstaffprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation e.g. Headmaster, Senior Math Teacher, Accountant, Office Assistant', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacherandstaffprofile',
            name='employee_type',
            field=models.CharField(choices=[('head_teacher', 'Head Teacher'), ('teacher', 'Teacher'), ('staff', 'Staff')], default='teacher', help_text='Select whether this profile belongs to a Head Teacher, Teacher or Staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherandstaffprofile',
            name='mother_name_bn',
            field=models.CharField(blank=True, help_text='মায়ের বাংলা নাম', max_length=150),
        ),
    ]
