# Generated by Django 5.2.5 on 2026-09-28 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0008_alter_teacherandstaffprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherandstaffprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacherandstaffprofile',
            name='user',
            field=models.OneToOneField(default=1, help_text='Linked user account created during Auth', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_staff_profile', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
