# Generated by Django 5.2.5 on 2026-04-25 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_is_id_card_generated_student_qr_code_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_type', models.CharField(choices=[('TRANSFER', 'Transfer Certificate (TC)'), ('CHARACTER', 'Character Certificate'), ('TESTIMONIAL', 'Testimonial'), ('BONAFIDE', 'Bonafide Certificate')], max_length=50)),
                ('reason_for_request', models.TextField()),
                ('new_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_class_attended', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_certificate', models.FileField(blank=True, null=True, upload_to='certificates/issued/%Y/%m/')),
                ('timeline_data', models.JSONField(blank=True, default=list)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Certificate Application',
                'db_table': 'app_documents_certificates',
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='certificates/attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.certificateapplication')),
            ],
            options={
                'db_table': 'app_documents_attachments',
            },
        ),
    ]
