# Generated by Django 5.2.5 on 2025-09-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academiconlineclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('For_Class', models.CharField(choices=[('Class 6', 'classs 6'), ('Class 7', 'class 7'), ('Class 8', 'class 8'), ('Class 9', 'class 9'), ('Class 10', 'class 10')], default='Class 6', max_length=50)),
                ('Section', models.CharField(choices=[('Section A', 'section A'), ('Section A', 'section A'), ('Section A', 'section A'), ('Section A', 'section A')], max_length=50)),
                ('Class_Topic', models.CharField(max_length=255)),
                ('Class_Date', models.DateField()),
                ('Class_Time', models.TimeField()),
                ('Password', models.CharField(max_length=255)),
                ('notify_parents', models.BooleanField(default=False)),
                ('Notification_Type', models.CharField(choices=[('Whatsapp & SMS', 'whatsapp & sms'), ('Whatsapp Only', 'whatsapp only'), ('SMS Only', 'sms only'), ('Email', 'email')], max_length=50)),
            ],
            options={
                'verbose_name': 'Class_Topic',
                'verbose_name_plural': 'Class_Topics',
            },
        ),
    ]
