# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academiconlineclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Topic', models.CharField(max_length=255)),
                ('Class_Date', models.DateField()),
                ('Class_Time', models.TimeField()),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
                ('Class_Link', models.URLField(blank=True, max_length=500, null=True)),
                ('notify_parents', models.BooleanField(default=False)),
                ('Notification_Type', models.CharField(choices=[('Whatsapp & SMS', 'whatsapp & sms'), ('Whatsapp Only', 'whatsapp only'), ('SMS Only', 'sms only'), ('Email', 'email')], max_length=50)),
                ('For_Class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.academicclass')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.section')),
            ],
            options={
                'verbose_name': 'Class_Topic',
                'verbose_name_plural': 'Class_Topics',
            },
        ),
    ]
