# Generated by Django 5.2.5 on 2025-09-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_online_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiconlineclass',
            name='Section',
            field=models.CharField(choices=[('Section A', 'section A'), ('Section B', 'section B'), ('Section C', 'section C'), ('Section D', 'section D')], max_length=50),
        ),
    ]
