# Generated by Django 5.2.5 on 2026-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_online_class', '0002_alter_academiconlineclass_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiconlineclass',
            name='Class_Link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='academiconlineclass',
            name='Password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
