# Generated by Django 5.2.5 on 2026-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('application_start', models.DateField()),
                ('application_end', models.DateField()),
                ('exam_date', models.DateField()),
                ('result_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
