# Generated by Django 5.2.5 on 2026-02-08 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_contactmessage_letterinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_slider',
            name='image',
            field=models.ImageField(help_text='Upload a slider image (JPG or PNG, Max 1MB)', upload_to='sliders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Slider Image (1080x720)'),
        ),
        migrations.AlterField(
            model_name='letterinfo',
            name='image',
            field=models.ImageField(help_text='Upload a later (JPG or PNG, Max 1MB)', upload_to='letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Later Picture (1080x1080)'),
        ),
    ]
