# Generated by Django 5.2.5 on 2025-11-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_category', models.CharField(choices=[('Fees', 'Student Fees Collection'), ('Bank', 'Bank Deposit'), ('Other', 'Other Deposit')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='deposit_vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
