# Generated by Django 5.2.5 on 2025-11-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_voucher_generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('deposit_category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DepositVoucher',
        ),
    ]
