# Generated by Django 5.2.5 on 2025-11-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_voucher_generate', '0002_expensevoucher_delete_depositvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensevoucher',
            name='deposit_category',
            field=models.CharField(choices=[('general', 'General'), ('exam', 'Exam'), ('govt. salary', 'Govt. Salary'), ('tuition fee', 'Tuition Fee'), ('science', 'Science')], max_length=100),
        ),
    ]
