# Generated by Django 5.2.5 on 2025-11-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_voucher_generate', '0003_alter_expensevoucher_deposit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensevoucher',
            name='voucher_no',
        ),
    ]
