# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('class_wise', 'Class-wise Fee'), ('individual', 'Individual Student Fee')], max_length=20)),
                ('fee_type', models.CharField(choices=[('tuition fee', 'Tuition Fee'), ('exam fee', 'Examination Fee'), ('registration fee', 'Registration Fee'), ('session fee', 'Session Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount assigned.', max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_period', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('select_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.academicclass')),
                ('select_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.section')),
            ],
        ),
        migrations.CreateModel(
            name='FormFilupAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('class_wise', 'Class-wise Fee'), ('individual', 'Individual Student Fee')], max_length=20)),
                ('fee_type', models.CharField(default='form filup', editable=False, max_length=50)),
                ('Printing_Xerox_Expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Printing/Xerox Expense')),
                ('Magazine_Fee_Expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Magazine Fee/Expense')),
                ('Sports_Fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sports Fee')),
                ('Cultural_Debate_Fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cultural/Debate Fee')),
                ('Victory_Day_Celebration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Victory Day Celebration')),
                ('Formation_of_various_clubs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Formation of various clubs')),
                ('Library', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Library')),
                ('Welfare_Poor_Fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Welfare/Poor Fund')),
                ('ICT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ICT')),
                ('Garden_Maintenance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Garden Maintenance')),
                ('Labratory', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Labratory')),
                ('scout_Red_Crescent_Celebration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Scout/Red-Crescent Celebration')),
                ('Common_Room', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Common Room')),
                ('Identity_Card', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Identity Card')),
                ('Essential_Expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Essential Expense')),
                ('Freshers_Farewell_Reception', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Freshers/Farewell Reception')),
                ('Medical_Service', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Medical Service')),
                ('Miscellaneous_Ancillary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Miscellaneous/Ancillary')),
                ('Development', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Development')),
                ('Electricity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Electricity')),
                ('Educational_Tour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Educational Tour')),
                ('Swimming_Training', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Swimming Training')),
                ('Retirement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Retirement')),
                ('Welfare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Welfare')),
                ('Mosque', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Mosque')),
                ('due_date', models.DateField()),
                ('payment_period', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('select_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.academicclass')),
                ('select_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_mm_class_and_section.section')),
            ],
        ),
    ]
