# Generated by Django 5.2.5 on 2025-12-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('class_wise', 'Class-wise Fee'), ('individual', 'Individual Student Fee')], max_length=20)),
                ('select_class', models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=50)),
                ('select_section', models.CharField(choices=[('section A', 'Section A'), ('section B', 'Section B'), ('section C', 'Section C'), ('section D', 'Section D')], max_length=50)),
                ('fee_type', models.CharField(choices=[('tuition fee', 'Tuition Fee'), ('exam fee', 'Examination Fee'), ('form_fillup fee', 'Form Fillup Fee'), ('registration fee', 'Registration Fee'), ('session fee', 'Session Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount assigned.', max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_period', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
