# Generated by Django 5.2.5 on 2025-12-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFilupAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Printing_Xerox_Expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Printing/Xerox Expense')),
                ('Magazine_Fee_Expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Magazine Fee/Expense')),
                ('Sports_Fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Sports Fee')),
                ('Cultural_Debate_Fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Cultural/Debate Fee')),
                ('Victory_Day_Celebration', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Victory Day Celebration')),
                ('Formation_of_various_clubs', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Formation of various clubs')),
                ('Library', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Library')),
                ('Welfare_Poor_Fund', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Welfare/Poor Fund')),
                ('ICT', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='ICT')),
                ('Garden_Maintenance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Garden Maintenance')),
                ('Labratory', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Labratory')),
                ('scout_Red_Crescent_Celebration', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='scout/Red-Crescent Celebration')),
                ('Common_Room', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Common Room')),
                ('Identity_Card', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Identity Card')),
                ('Essential_Expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Essential Expense')),
                ('Freshers_Farewell_Reception', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Freshers/Farewell Reception')),
                ('Medical_Service', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Medical Service')),
                ('Miscellaneous_Ancillary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Miscellaneous/Ancillary')),
                ('Development', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Development')),
                ('Electricity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Electricity')),
                ('Educational_Tour', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Educational Tour')),
                ('Swimming_Training', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Swimming Training')),
                ('Retirement', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Retirement')),
                ('Welfare', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Welfare (Duplicate field, maybe delete later)')),
                ('Mosque', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Mosque')),
            ],
        ),
        migrations.CreateModel(
            name='FormFillupSubAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_amounts', to='account_mm_create_fee.createfee')),
            ],
        ),
    ]
