# Generated by Django 5.2.5 on 2025-12-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0002_formfilupamount_formfillupsubamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfillupsubamount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='formfillupsubamount',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
