# Generated by Django 5.2.5 on 2025-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0003_alter_formfillupsubamount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfillupsubamount',
            name='fee_assignment',
        ),
        migrations.DeleteModel(
            name='FormFilupAmount',
        ),
        migrations.DeleteModel(
            name='FormFillupSubAmount',
        ),
    ]
