# Generated by Django 5.2.5 on 2025-12-22 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0004_remove_formfillupsubamount_fee_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TUITION', 'Tuition Fee'), ('SEMESTER', 'Semester Fee'), ('EXAMINATION', 'Examination Fee'), ('FORM_FILLUP', 'Form Fillup Fee'), ('LIBRARY', 'Library Fee'), ('TRANSPORT', 'Transport Fee')], max_length=50, unique=True)),
                ('input_type', models.CharField(choices=[('SINGLE', 'Single Amount'), ('MULTIPLE', 'Multiple Sub-items')], default='SINGLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('CLASS_WISE', 'Class-wise Fee'), ('INDIVIDUAL', 'Individual Student Fee')], max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_items_amounts', models.JSONField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('payment_period', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_mm_create_fee.feetype')),
            ],
        ),
        migrations.DeleteModel(
            name='CreateFee',
        ),
        migrations.AddField(
            model_name='feesubitem',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='account_mm_create_fee.feetype'),
        ),
    ]
