# Generated by Django 5.2.5 on 2025-12-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0005_feesubitem_feetype_studentfee_delete_createfee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='feetype',
            name='input_type',
            field=models.CharField(choices=[('SINGLE', 'Single Amount (Manual)'), ('MULTIPLE', 'Multiple Sub-items (JSON)')], default='SINGLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='assignment_type',
            field=models.CharField(choices=[('CLASS_WISE', 'Class-wise Fee')], default='CLASS_WISE', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='payment_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time'), ('SEMESTER', 'Semester')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='section',
            field=models.CharField(max_length=10),
        ),
    ]
