# Generated by Django 5.2.5 on 2025-12-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0006_remove_studentfee_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='payment_period',
            field=models.CharField(max_length=20),
        ),
    ]
