# Generated by Django 5.2.5 on 2025-12-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0007_alter_studentfee_payment_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('class_wise', 'Class-wise Fee'), ('individual', 'Individual Student Fee')], max_length=20)),
                ('select_class', models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=50)),
                ('select_section', models.CharField(choices=[('section A', 'Section A'), ('section B', 'Section B'), ('section C', 'Section C'), ('section D', 'Section D')], max_length=50)),
                ('fee_type', models.CharField(choices=[('tuition fee', 'Tuition Fee'), ('exam fee', 'Examination Fee'), ('form_fillup fee', 'Form Fillup Fee'), ('registration fee', 'Registration Fee'), ('session fee', 'Session Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount assigned.', max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_period', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormFilupAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Printing_Xerox_Expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Printing/Xerox Expense')),
                ('Magazine_Fee_Expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Magazine Fee/Expense')),
                ('Sports_Fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Sports Fee')),
                ('Cultural_Debate_Fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Cultural/Debate Fee')),
                ('Victory_Day_Celebration', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Victory Day Celebration')),
                ('Formation_of_various_clubs', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Formation of various clubs')),
                ('Library', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Library')),
                ('Welfare_Poor_Fund', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Welfare/Poor Fund')),
                ('ICT', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='ICT')),
                ('Garden_Maintenance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Garden Maintenance')),
                ('Labratory', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Labratory')),
                ('scout_Red_Crescent_Celebration', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='scout/Red-Crescent Celebration')),
                ('Common_Room', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Common Room')),
                ('Identity_Card', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Identity Card')),
                ('Essential_Expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Essential Expense')),
                ('Freshers_Farewell_Reception', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Freshers/Farewell Reception')),
                ('Medical_Service', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Medical Service')),
                ('Miscellaneous_Ancillary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Miscellaneous/Ancillary')),
                ('Development', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Development')),
                ('Electricity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Electricity')),
                ('Educational_Tour', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Educational Tour')),
                ('Swimming_Training', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Swimming Training')),
                ('Retirement', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Retirement')),
                ('Welfare', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Welfare (Duplicate field, maybe delete later)')),
                ('Mosque', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Mosque')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='fee_type',
        ),
        migrations.DeleteModel(
            name='FeeSubItem',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='StudentFee',
        ),
    ]
