# Generated by Django 5.2.5 on 2025-12-31 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_create_fee', '0008_createfee_formfilupamount_remove_studentfee_fee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfilupamount',
            name='assignment_type',
            field=models.CharField(choices=[('class_wise', 'Class-wise Fee'), ('individual', 'Individual Student Fee')], default='class_wise', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfilupamount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfilupamount',
            name='due_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfilupamount',
            name='fee_type',
            field=models.CharField(default='form filup', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='formfilupamount',
            name='payment_period',
            field=models.CharField(default='Not Specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfilupamount',
            name='select_class',
            field=models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], default='class 6', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfilupamount',
            name='select_section',
            field=models.CharField(choices=[('section A', 'Section A'), ('section B', 'Section B'), ('section C', 'Section C'), ('section D', 'Section D')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createfee',
            name='fee_type',
            field=models.CharField(choices=[('tuition fee', 'Tuition Fee'), ('exam fee', 'Examination Fee'), ('registration fee', 'Registration Fee'), ('session fee', 'Session Fee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Common_Room',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Common Room'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Cultural_Debate_Fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cultural/Debate Fee'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Development',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Development'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Educational_Tour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Educational Tour'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Electricity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Electricity'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Essential_Expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Essential Expense'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Formation_of_various_clubs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Formation of various clubs'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Freshers_Farewell_Reception',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Freshers/Farewell Reception'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Garden_Maintenance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Garden Maintenance'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='ICT',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ICT'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Identity_Card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Identity Card'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Labratory',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Labratory'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Library',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Magazine_Fee_Expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Magazine Fee/Expense'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Medical_Service',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Medical Service'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Miscellaneous_Ancillary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Miscellaneous/Ancillary'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Mosque',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Mosque'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Printing_Xerox_Expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Printing/Xerox Expense'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Retirement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Retirement'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Sports_Fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sports Fee'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Swimming_Training',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Swimming Training'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Victory_Day_Celebration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Victory Day Celebration'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Welfare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Welfare'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='Welfare_Poor_Fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Welfare/Poor Fund'),
        ),
        migrations.AlterField(
            model_name='formfilupamount',
            name='scout_Red_Crescent_Celebration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Scout/Red-Crescent Celebration'),
        ),
    ]
