# Generated by Django 5.2.5 on 2026-07-17 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_roles_permissions', '0002_remove_rolepermission_feature_and_more'),
        ('userauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth_roles_permissions.role'),
        ),
    ]
