# Generated by Django 5.2.5 on 2025-10-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exmquestionbank',
            name='class_name',
            field=models.CharField(choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=20),
        ),
    ]
