# Generated by Django 5.2.5 on 2026-08-02 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_create_subject', '0002_rename_subject_subject_name'),
        ('exam_mm_question_bank', '0004_alter_exmquestionbank_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exmquestionbank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examquestionbank', to='academic_create_subject.subject_name'),
        ),
    ]
