# Generated by Django 5.2.5 on 2025-09-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_admission_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('exam_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('notify_parents', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='whatsapp_sms', max_length=50)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_date', '-exam_time'],
            },
        ),
    ]
