# Generated by Django 5.2.5 on 2025-09-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission_exam',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'Whatsapp'), ('whatsapp & sms', 'Whatsapp & SMS')], default='whatsapp_sms', max_length=50),
        ),
    ]
