# Generated by Django 5.2.5 on 2026-09-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_teacher', '0006_remove_teacher_user_remove_teacherss_user_and_more'),
        ('teacher_mm_teacher_leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='teacher_mm_teacher.teacherandstaffprofile'),
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='teacher_mm_teacher.teacherandstaffprofile'),
        ),
    ]
