# Generated by Django 5.2.5 on 2025-12-02 11:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_add_user_link_and_extended_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Salary month (stored as first day of month, e.g., 2025-05-01)')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Base salary amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('yearly', 'Yearly')], default='monthly', help_text='How often salary is paid', max_length=20)),
                ('payment_method', models.CharField(choices=[('direct_deposit', 'Direct Deposit'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check')], default='bank_transfer', help_text='Method of payment', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payment status', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date and time when payment was made', null=True)),
                ('comments', models.TextField(blank=True, default='', help_text='Additional notes or comments about this salary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salaries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The employee/teacher this salary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='teacher.teacher')),
                ('paid_by', models.ForeignKey(blank=True, help_text='User who processed the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Salary',
                'verbose_name_plural': 'Employee Salaries',
                'db_table': 'employee_salary',
                'ordering': ['-month', 'employee__user__name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('housing', 'Housing Allowance'), ('transport', 'Transport Allowance'), ('medical', 'Medical Allowance'), ('meal', 'Meal Allowance'), ('phone', 'Phone Allowance'), ('education', 'Education Allowance'), ('overtime', 'Overtime Pay'), ('bonus', 'Bonus'), ('other', 'Other')], default='other', help_text='Type of allowance', max_length=20)),
                ('name', models.CharField(help_text='Name/description of the allowance', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Allowance amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary', models.ForeignKey(help_text='The salary record this allowance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='salary.employeesalary')),
            ],
            options={
                'verbose_name': 'Salary Allowance',
                'verbose_name_plural': 'Salary Allowances',
                'db_table': 'salary_allowance',
                'ordering': ['allowance_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('income_tax', 'Income Tax'), ('pension', 'Pension Fund'), ('health_insurance', 'Health Insurance'), ('life_insurance', 'Life Insurance'), ('loan', 'Loan Repayment'), ('advance', 'Salary Advance'), ('late_penalty', 'Late Penalty'), ('absence', 'Absence Deduction'), ('other', 'Other')], default='other', help_text='Type of deduction', max_length=20)),
                ('name', models.CharField(help_text='Name/description of the deduction', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Deduction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary', models.ForeignKey(help_text='The salary record this deduction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='salary.employeesalary')),
            ],
            options={
                'verbose_name': 'Salary Deduction',
                'verbose_name_plural': 'Salary Deductions',
                'db_table': 'salary_deduction',
                'ordering': ['deduction_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['month'], name='employee_sa_month_6e191d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['payment_status'], name='employee_sa_payment_93b265_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['employee', 'month'], name='employee_sa_employe_a80dfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('employee', 'month')},
        ),
    ]
