# Generated by Django 5.2.5 on 2025-12-22 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_employeesalary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'ordering': ['-created_at', 'employee__name'], 'verbose_name': 'Employee Salary', 'verbose_name_plural': 'Employee Salaries'},
        ),
        migrations.RemoveIndex(
            model_name='employeesalary',
            name='employee_sa_month_6e191d_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeesalary',
            name='employee_sa_employe_a80dfa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='department',
            field=models.CharField(default='General', help_text="Employee's department at time of salary assignment", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='position',
            field=models.CharField(default='Employee', help_text="Employee's position/role at time of salary assignment", max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['department'], name='employee_sa_departm_b33b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['position'], name='employee_sa_positio_d7f5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['employee'], name='employee_sa_employe_0f32bd_idx'),
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='month',
        ),
    ]
