# Generated by Django 5.2.5 on 2025-12-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_employeesalary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='department',
            field=models.CharField(default='General', help_text="Employee's department at time of salary assignment", max_length=100),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='position',
            field=models.CharField(default='Employee', help_text="Employee's position/role at time of salary assignment", max_length=100),
        ),
    ]
