# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Teaching', 'Teaching'), ('Administration', 'Administration'), ('Accounts', 'Accounts')], default='Teaching', max_length=100)),
                ('position', models.CharField(choices=[('Science Teacher', 'Science Teacher'), ('Arts Teacher', 'Arts Teacher'), ('English Teacher', 'English Teacher'), ('Senior Staff', 'Senior Staff'), ('Junior Staff', 'Junior Staff')], max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Weekly', 'Weekly')], default='Monthly', max_length=50)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking')], max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role__name__in': ['Teacher', 'Staff']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('payment_date', models.DateField()),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('Extra Class', 'Extra Class'), ('Overtime', 'Overtime')], max_length=100)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_works', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
    ]
