# Generated by Django 5.2.5 on 2026-04-26 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(help_text='User role based department', max_length=100)),
                ('position', models.CharField(choices=[('Science Teacher', 'Science Teacher'), ('Arts Teacher', 'Arts Teacher'), ('English Teacher', 'English Teacher'), ('Senior Staff', 'Senior Staff'), ('Junior Staff', 'Junior Staff')], max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_frequency', models.CharField(default='Monthly', max_length=50)),
                ('allowance_title', models.CharField(blank=True, max_length=255, null=True)),
                ('allowance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deduction_title', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking')], max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['Teacher', 'Staff']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
