# Generated by Django 5.2.5 on 2026-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_add_salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='payment_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Weekly', 'Weekly')], default='Monthly', max_length=50),
        ),
    ]
