# Generated by Django 5.2.5 on 2026-04-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_add_salary', '0002_alter_salaryrecord_payment_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='allowance_amount',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='allowance_title',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='deduction_title',
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='department',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Administration', 'Administration'), ('Accounts', 'Accounts')], default='Teaching', max_length=100),
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
    ]
