# Generated by Django 5.2.5 on 2026-04-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_add_salary', '0003_remove_salaryrecord_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
