# Generated by Django 5.2.5 on 2026-05-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_add_salary', '0004_alter_allowance_amount_alter_allowance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ExtraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('Extra Class', 'Extra Class'), ('Overtime', 'Overtime')], max_length=100)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_works', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
    ]
