# Generated by Django 5.2.5 on 2026-05-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_add_salary', '0005_salaryrecord_status_extrawork'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('payment_date', models.DateField()),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='teacher_mm_add_salary.salaryrecord')),
            ],
        ),
    ]
