# Generated by Django 5.2.5 on 2026-07-18 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_mm_add_salary', '0006_paymenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['Teacher', 'Staff']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
