# Generated by Django 5.2.5 on 2026-08-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', models.CharField(choices=[('student salary', 'Student Salary'), ('session fees', 'Session Fees'), ('exam fees', 'Exam Fees'), ('form filup', 'Form Filup'), ('shop rent', 'Shop Rent'), ('land rent', 'Land Rent'), ('donation', 'Donation')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='income_vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
