# Generated by Django 5.2.5 on 2025-11-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mm_income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_income',
            name='income_category',
            field=models.CharField(choices=[('student salary', 'Student Salary'), ('session fees', 'Session Fees'), ('exam fees', 'Exam Fees'), ('form filup', 'Form Filup'), ('shop rent', 'Shop Rent'), ('land rent', 'Land Rent'), ('donation', 'Donation')], max_length=50),
        ),
    ]
