# Generated by Django 5.2.5 on 2026-02-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mm_photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('poster_image', models.ImageField(upload_to='video_posters/')),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
