# Generated by Django 5.2.5 on 2026-07-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_mm_photo_gallery', '0002_videogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='poster_image',
        ),
    ]
