# Generated by Django 5.2.5 on 2026-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_school_archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_archive_document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
