# Generated by Django 5.2.5 on 2026-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_school_archive', '0002_alter_school_archive_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_archive_document',
            name='doc_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('docx', 'DOCX')], max_length=100),
        ),
    ]
