# Generated by Django 5.2.5 on 2026-01-17 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.DateField()),
                ('year_end', models.DateField()),
                ('academic_year_label', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Academic Calendars',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('academic', 'Academic Holiday'), ('national', 'National Holiday'), ('religious', 'Religious Holiday'), ('other', 'Other Holiday')], max_length=20)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='institute_mm_academic_calender.academiccalendar')),
            ],
        ),
    ]
