# Generated by Django 5.2.5 on 2026-01-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_mm_academic_calender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='calendar',
        ),
    ]
