# Generated by Django 5.2.5 on 2026-02-21 10:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_number', models.CharField(max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('editor_in_chief', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('cover_image', models.ImageField(help_text='Upload a cover image (JPG or PNG, Max 1MB)', upload_to='magazine_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Cover Image (1080x1080)')),
                ('keywords', models.CharField(help_text='Comma separated keywords', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_title', models.CharField(max_length=255)),
                ('issue_number', models.CharField(max_length=100)),
                ('target_publication_date', models.DateField()),
                ('publication_description', models.TextField(blank=True, null=True)),
                ('content_submission_deadline', models.DateField()),
                ('review_deadline', models.DateField()),
                ('initial_content_plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_tasks', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(related_name='team_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
