# Generated by Django 5.2.5 on 2026-02-21 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mm_magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('content_category', models.CharField(choices=[('news', 'News'), ('feature', 'Feature'), ('interview', 'Interview'), ('opinion', 'Opinion')], max_length=50)),
                ('content_summary', models.TextField()),
                ('uploaded_file', models.FileField(upload_to='submissions/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Review', 'Under Review')], default='Draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('target_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='event_mm_magazine.scheduledpublication')),
            ],
        ),
    ]
