# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.academicclass')),
                ('marked_by', models.ForeignKey(limit_choices_to={'role__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['classname', 'section', 'date'], name='attendance__classna_83a371_idx'), models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx')],
                'unique_together': {('student', 'classname', 'section', 'date')},
            },
        ),
    ]
