# Generated by Django 5.2.5 on 2026-07-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_class_routine', '0003_alter_classroutine_subject'),
        ('attendance', '0001_initial'),
        ('students', '0002_student_is_id_card_generated_student_qr_code_data_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__class_s_860ff4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'classname', 'section', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='classname',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['classname', 'section', 'date'], name='attendance__classna_63a31a_idx'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_section',
        ),
    ]
