# Generated by Django 5.2.5 on 2026-08-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_attendance__class_s_860ff4_idx_and_more'),
        ('teacher_mm_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_mm_teacher.teacher'),
        ),
    ]
