# Generated by Django 5.2.5 on 2026-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Attendance', 'Attendance'), ('Fees', 'Fees'), ('Exam', 'Exam'), ('Event', 'Event'), ('Notice', 'General Notice'), ('Admission', 'Admission'), ('Result', 'Result'), ('Holiday', 'Holiday')], default='Notice', max_length=50)),
                ('template_content', models.TextField()),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
    ]
