# Generated by Django 5.2.5 on 2026-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication_canter_sms_template', '0002_smssenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSSentHistory',
        ),
    ]
