# Generated by Django 5.2.5 on 2026-04-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0002_student_is_id_card_generated_student_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'ordering': ['-marks_obtained']},
        ),
        migrations.AddField(
            model_name='examadmitcard',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='examseatplan',
            unique_together={('exam_setup', 'student')},
        ),
    ]
