# Generated by Django 5.2.5 on 2026-04-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_studentresult_options_and_more'),
        ('staff', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherduty',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile'),
        ),
    ]
