# Generated by Django 5.2.5 on 2026-04-25 05:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_class_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_class', models.CharField(choices=[('class 6', 'class 6'), ('class 9', 'class 9'), ('other', 'Other')], max_length=100, verbose_name='Desired Class for Admission')),
                ('student_name_english', models.CharField(max_length=255, verbose_name="Student's Name (English)")),
                ('student_name_bangla', models.CharField(blank=True, max_length=255, null=True, verbose_name="Student's Name (Bangla)")),
                ('birth_registration_number', models.CharField(max_length=100, unique=True, verbose_name='Birth Registration Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('religion', models.CharField(choices=[('islam', 'Islam'), ('hindu', 'Hindu'), ('buddhist', 'Buddhist'), ('christian', 'Christian'), ('other', 'Other'), ('not_specified', 'Not Specified')], max_length=50, verbose_name='Religion')),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile photo (JPG or PNG, Max 1MB)', null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('admin_form_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_status', models.CharField(choices=[('pending', 'Pending'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20, verbose_name='Admission Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sibling_identification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name_en', models.CharField(max_length=255)),
                ('father_name_bn', models.CharField(max_length=255)),
                ('father_nid_number', models.CharField(max_length=20, unique=True)),
                ('father_is_deceased', models.BooleanField(default=False)),
                ('mother_name_en', models.CharField(max_length=255)),
                ('mother_name_bn', models.CharField(max_length=255)),
                ('mother_nid_number', models.CharField(max_length=20, unique=True)),
                ('mother_is_deceased', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=20)),
                ('whatsapp_available', models.BooleanField(default=False)),
                ('guardian_profession', models.CharField(max_length=255)),
                ('family_annual_income', models.CharField(default=0, max_length=100)),
                ('present_address_village', models.CharField(max_length=255)),
                ('present_address_post_office', models.CharField(max_length=255)),
                ('present_address_sub_district', models.CharField(max_length=255)),
                ('present_address_district', models.CharField(max_length=255)),
                ('is_permanent_same_as_present', models.BooleanField(default=False)),
                ('permanent_address_village', models.CharField(max_length=255)),
                ('permanent_address_post_office', models.CharField(max_length=255)),
                ('permanent_address_sub_district', models.CharField(max_length=255)),
                ('permanent_address_district', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('School_address', models.CharField(max_length=255)),
                ('passing_class', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('passing_year', models.IntegerField()),
                ('sibling_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('special_skills', models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Dance', 'Dance'), ('Singing', 'Singing'), ('Ham/Naat', 'Ham/Naat'), ('Qirat', 'Qirat'), ('Chess', 'Chess'), ('Badminton', 'Badminton'), ('Shot Put', 'Shot Put'), ('Swimming', 'Swimming')], max_length=255, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student Admission Form',
                'verbose_name_plural': 'Student Admission Forms',
                'db_table': 'student_admission_studentadmission',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='LotterySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_class', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField()),
                ('lottery_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_sessions', to='academics.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_address', models.CharField(blank=True, max_length=500, null=True)),
                ('class_studying_in', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gpa_obtained', models.CharField(blank=True, max_length=10, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previous_academic_record', to='admissions.studentadmission')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='admission_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.studentadmission')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionSkillLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionskill')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='admissions.studentadmission')),
            ],
            options={
                'unique_together': {('admission', 'skill')},
            },
        ),
    ]
