# Generated by Django 5.2.5 on 2026-04-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmission',
            name='School_address',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='passing_class',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='sibling_id_number',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='special_skills',
        ),
    ]
