# Generated by Django 5.2.5 on 2026-04-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_class_level'),
        ('admissions', '0002_remove_studentadmission_school_address_and_more'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM student_admission_studentadmission;'),
        migrations.AlterField(
            model_name='studentadmission',
            name='desired_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class', verbose_name='Desired Class for Admission'),
        ),
    ]
