# Generated by Django 5.2.5 on 2026-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_studentadmission_desired_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterysession',
            name='academic_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='desired_class',
            field=models.CharField(default='', max_length=100, verbose_name='Desired Class for Admission'),
            preserve_default=False,
        ),
    ]
