from django.db import migrations


def create_missing_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admissions_admissionskill (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(50) NOT NULL UNIQUE
            );
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admissions_lotterysession (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academic_year varchar(100) NOT NULL,
                target_class varchar(100) NOT NULL,
                total_seats integer NOT NULL,
                lottery_date date NOT NULL,
                is_completed boolean NOT NULL,
                created_at timestamp with time zone NOT NULL
            );
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admissions_previousacademicrecord (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                school_name varchar(255) NOT NULL,
                school_address varchar(500) NULL,
                class_studying_in varchar(50) NULL,
                roll_number varchar(50) NULL,
                gpa_obtained varchar(10) NULL,
                passing_year varchar(4) NULL,
                admission_id bigint NOT NULL UNIQUE
                    REFERENCES student_admission_studentadmission (id)
                    DEFERRABLE INITIALLY DEFERRED
            );
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admissions_admissiondocument (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                document_type varchar(50) NOT NULL,
                "file" varchar(100) NOT NULL,
                uploaded_at timestamp with time zone NOT NULL,
                admission_id bigint NOT NULL
                    REFERENCES student_admission_studentadmission (id)
                    DEFERRABLE INITIALLY DEFERRED
            );
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admissions_admissionskilllink (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                skill_id bigint NOT NULL
                    REFERENCES admissions_admissionskill (id)
                    DEFERRABLE INITIALLY DEFERRED,
                admission_id bigint NOT NULL
                    REFERENCES student_admission_studentadmission (id)
                    DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT admissions_skilllink_admission_skill_uniq
                    UNIQUE (admission_id, skill_id)
            );
        """)
        cursor.execute("CREATE INDEX IF NOT EXISTS admissions_doc_admission_idx ON admissions_admissiondocument (admission_id);")
        cursor.execute("CREATE INDEX IF NOT EXISTS admissions_link_skill_idx ON admissions_admissionskilllink (skill_id);")
        cursor.execute("CREATE INDEX IF NOT EXISTS admissions_link_admission_idx ON admissions_admissionskilllink (admission_id);")


def drop_missing_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS admissions_admissionskilllink;")
        cursor.execute("DROP TABLE IF EXISTS admissions_admissiondocument;")
        cursor.execute("DROP TABLE IF EXISTS admissions_previousacademicrecord;")
        cursor.execute("DROP TABLE IF EXISTS admissions_lotterysession;")
        cursor.execute("DROP TABLE IF EXISTS admissions_admissionskill;")


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_lotterysession_academic_year_and_more'),
    ]

    operations = [
        migrations.RunPython(create_missing_tables, drop_missing_tables),
    ]