# Generated by Django 5.2.5 on 2026-05-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication_canter_sms_template', '0003_delete_smssenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipients', models.TextField()),
                ('group', models.CharField(max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication_canter_sms_template.smstemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
