# Generated by Django 5.2.5 on 2026-09-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_center_sentsms', '0001_initial'),
        ('students', '0003_alter_student_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='টেমপ্লেটের নাম (যেমন: ফি রসিদ, নোটিশ)', max_length=100)),
                ('content_id', models.CharField(blank=True, help_text='sms.net.bd Content ID (যদি থাকে)', max_length=50, null=True)),
                ('message_body', models.TextField(help_text='মেসেজের মূল টেক্সট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('request_id', models.CharField(blank=True, help_text='sms.net.bd Request ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_histories', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'SMS Histories',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='SMSSentHistory',
        ),
    ]
