# Generated by Django 5.2.5 on 2025-10-14 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=32)),
                ('admission_number', models.CharField(max_length=64)),
                ('admission_date', models.DateField()),
                ('roll_number', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('alumni', 'Alumni'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('class_name', models.CharField(blank=True, choices=[('class 6', 'Class 6'), ('class 7', 'Class 7'), ('class 8', 'Class 8'), ('class 9', 'Class 9'), ('class 10', 'Class 10')], max_length=64, null=True)),
                ('section', models.CharField(choices=[('section A', 'Section A'), ('section B', 'Section B'), ('section C', 'Section C'), ('section D', 'Section D')], max_length=32)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('house', models.CharField(max_length=64)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('hindu', 'Hindu'), ('christian', 'Christian'), ('buddhism', 'Buddhism'), ('others', 'Others')], max_length=64, null=True)),
                ('category', models.CharField(blank=True, choices=[('general', 'General'), ('vocational', 'Vocational')], max_length=16, null=True)),
                ('primary_contact_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Enter a valid phone number with country code if applicable.')])),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('caste', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=64, null=True)),
                ('scholarship', models.CharField(choices=[('hsp', 'HSP'), ('dte', 'DTE'), ('general scholarship', 'Genral Scholarship'), ('talentpul scholarship', 'Talentpul Scholarship'), ('hf', 'HF'), ('f', 'F')], max_length=25)),
                ('photo', models.ImageField(blank=True, help_text='Upload a profile photo (JPG or PNG, Max 1MB)', null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Admission',
                'verbose_name_plural': 'Student Admissions',
                'indexes': [models.Index(fields=['academic_year', 'admission_number'], name='student_pro_academi_96f08e_idx'), models.Index(fields=['class_name', 'section'], name='student_pro_class_n_da9d33_idx')],
                'unique_together': {('academic_year', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentGurdianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_photo', models.ImageField(blank=True, help_text='Upload a profile photo (JPG or PNG, Max 1MB)', null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('father_name', models.CharField(max_length=100)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_nid_or_birth_certificate', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_photo', models.ImageField(blank=True, help_text='Upload a profile photo (JPG or PNG, Max 1MB)', null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_nid_or_birth_certificate', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_type', models.CharField(choices=[('Parent', 'Parent'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Parent', max_length=20)),
                ('guardian_photo', models.ImageField(blank=True, help_text='Upload a profile photo (JPG or PNG, Max 1MB)', null=True, upload_to='student_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Picture (300x300)')),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_address', models.TextField(blank=True, null=True)),
                ('sibling_studying_same_school', models.BooleanField(default=False)),
                ('sibling_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sibling_admission_no', models.CharField(blank=True, max_length=50, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='student_profile.studentpersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_point', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='documents/medical/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='documents/transfer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('medical_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Other', 'Other')], max_length=10, null=True)),
                ('Disease', models.CharField(blank=True, max_length=100, null=True)),
                ('medication', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('previous_school_address', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('admission_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('sports', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='student_profile.studentpersonalinfo')),
            ],
        ),
    ]
