# Generated by Django 5.2.5 on 2025-10-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadditionalinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='student_profile.studentpersonalinfo'),
        ),
        migrations.AlterField(
            model_name='studentgurdianinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_info', to='student_profile.studentpersonalinfo'),
        ),
    ]
