# Generated by Django 5.2.5 on 2026-03-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mm_attendance', '0001_initial'),
        ('student_profile', '0002_alter_studentadditionalinfo_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_attendances', to='student_profile.studentpersonalinfo')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Library_Attendance',
        ),
    ]
