# Generated by Django 5.2.5 on 2026-03-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mm_attendance', '0002_libraryattendance_delete_library_attendance'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Library_student_id', models.CharField(max_length=20)),
                ('book_name', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='LibraryAttendance',
        ),
    ]
