# Generated by Django 5.2.5 on 2026-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mm_attendance', '0003_library_attendance_delete_libraryattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_attendance',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
