# Generated by Django 5.2.5 on 2026-04-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mm_attendance', '0004_alter_library_attendance_exit_time'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library_attendance',
            name='Library_student_id',
        ),
        migrations.AlterField(
            model_name='library_attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_attendances', to='students.student'),
        ),
    ]
