# Generated by Django 5.2.5 on 2026-04-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_mm_attendance', '0006_library_attendance_library_student_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library_Attendance',
        ),
    ]
