# Generated by Django 5.2.5 on 2026-05-17 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_mm_attendance', '0007_delete_library_attendance'),
        ('library_mm_book_list', '0001_initial'),
        ('students', '0002_student_is_id_card_generated_student_qr_code_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_attendances', to='library_mm_book_list.book_model')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_attendances', to='students.student')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
