# Generated by Django 5.2.5 on 2026-02-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_mm_Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_achieved', models.DateField()),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Arts & Culture', 'Arts & Culture')], max_length=50)),
                ('description', models.TextField()),
                ('students_involved', models.TextField(help_text='Enter names separated by commas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
