# Generated by Django 5.2.5 on 2026-01-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_mm_book_list', '0001_initial'),
        ('student_profile', '0002_alter_studentadditionalinfo_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDistributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_mm_book_list.book_model')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.studentpersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='LetterDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('Reminder', 'Reminder'), ('Fine', 'Fine'), ('Event', 'Event')], max_length=50)),
                ('recipient', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Acknowledged', 'Acknowledged')], default='Pending', max_length=20)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.studentpersonalinfo')),
            ],
        ),
    ]
