# Generated by Django 5.2.5 on 2026-07-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_roles_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
    ]
