# Generated by Django 5.2.5 on 2026-07-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_roles_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]