# Generated by Django 5.2.5 on 2026-07-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_roles_permissions', '0002_remove_rolepermission_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('feature_slug', models.CharField(max_length=100)),
                ('can_create', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to='user_auth_roles_permissions.role')),
            ],
            options={
                'unique_together': {('role', 'app_name', 'feature_slug')},
            },
        ),
    ]
