# Generated by Django 5.2.5 on 2026-07-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_roles_permissions', '0003_rolepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='app_name',
            new_name='feature_name',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'feature_name', 'feature_slug')},
        ),
    ]
