# Generated by Django 5.2.5 on 2026-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_roles_permissions', '0004_rename_app_name_rolepermission_feature_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='group_name',
            field=models.CharField(default=33, max_length=100),
            preserve_default=False,
        ),
    ]
