# Generated by Django 5.2.5 on 2026-07-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_roles_permissions', '0005_rolepermission_group_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user_auth_roles_permissions.role'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_slug', models.CharField(max_length=100)),
                ('can_create', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('feature_name', 'feature_slug')},
            },
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='user_auth_roles_permissions.permission'),
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='feature_name',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='feature_slug',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='group_name',
        ),
    ]
