# Generated by Django 5.2.5 on 2026-08-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_create_subject', '0002_rename_subject_subject_name'),
        ('students', '0002_student_is_id_card_generated_student_qr_code_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('number_of_benches', models.PositiveIntegerField(default=20)),
                ('capacity_per_bench', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift'), ('day', 'Day Shift')], default='morning', max_length=15)),
                ('bench_number', models.PositiveIntegerField()),
                ('seat_label', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='exam_mm_seat_mm.roomconfiguration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='academic_create_subject.subject_name')),
            ],
            options={
                'unique_together': {('room', 'bench_number', 'seat_label', 'shift', 'exam_date')},
            },
        ),
    ]
