# Generated by Django 5.2.5 on 2026-08-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_mm_class_and_section', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('number_of_benches', models.PositiveIntegerField(default=0)),
                ('students_per_bench', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning Shift'), ('Day', 'Day Shift')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.academicclass')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='exam_mm_seat_mm.examsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='exam_mm_seat_mm.examroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_mm_class_and_section.section')),
            ],
            options={
                'unique_together': {('exam_session', 'room', 'class_name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_number', models.PositiveIntegerField()),
                ('seat_label', models.CharField(max_length=20)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='exam_mm_seat_mm.examsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='exam_mm_seat_mm.examroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seats', to='students.student')),
            ],
            options={
                'unique_together': {('exam_session', 'room', 'bench_number', 'student')},
            },
        ),
    ]
