# Generated by Django 5.2.5 on 2026-09-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_seat_mm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroom',
            name='iiu',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
