# Generated by Django 5.2.5 on 2026-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_seat_mm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatallocation',
            name='class_name',
            field=models.CharField(blank=True, choices=[('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='section_name',
            field=models.CharField(blank=True, choices=[('Section A', 'Section A'), ('Section B', 'Section B'), ('Section C', 'Section C'), ('Section D', 'Section D')], max_length=20, null=True),
        ),
    ]
