# Generated by Django 5.2.5 on 2026-08-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_mm_seat_mm', '0002_seatallocation_class_name_and_more'),
        ('students', '0002_student_is_id_card_generated_student_qr_code_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('number_of_benches', models.PositiveIntegerField(default=0)),
                ('students_per_bench', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning Shift'), ('Day', 'Day Shift')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='seatallocation',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='seatallocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seatallocation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='seatallocation',
            name='subject',
        ),
        migrations.CreateModel(
            name='RoomClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10')], max_length=20)),
                ('section', models.CharField(choices=[('Section A', 'Section A'), ('Section B', 'Section B'), ('Section C', 'Section C'), ('Section D', 'Section D')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='exam_mm_seat_mm.examsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='exam_mm_seat_mm.examroom')),
            ],
            options={
                'unique_together': {('exam_session', 'room', 'class_name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_number', models.PositiveIntegerField()),
                ('seat_label', models.CharField(max_length=20)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='exam_mm_seat_mm.examsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='exam_mm_seat_mm.examroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seats', to='students.student')),
            ],
            options={
                'unique_together': {('exam_session', 'room', 'bench_number', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='RoomConfiguration',
        ),
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
    ]
