# Generated by Django 5.2.5 on 2026-02-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('roll', models.IntegerField(unique=True)),
                ('class_name', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50)),
                ('section', models.CharField(choices=[('section A', 'Section A'), ('section B', 'Section B'), ('section C', 'Section C'), ('section D', 'Section D')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('achievement', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
