# Generated by Django 5.2.5 on 2026-02-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_mm_top_students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentTop',
        ),
    ]
