# Generated by Django 5.2.5 on 2026-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Laboratory Equipment', 'Laboratory Equipment'), ('Furniture', 'Furniture'), ('Educational Materials', 'Educational Materials')], max_length=100)),
                ('location_or_sub_category', models.CharField(help_text='যেমন: Dress Making, Science, ICT', max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('total_capacity', models.IntegerField(default=0)),
                ('reorder_threshold', models.IntegerField(default=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
