# Generated by Django 5.2.5 on 2026-04-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_mm_stock_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='location_or_sub_category',
            field=models.CharField(max_length=100),
        ),
    ]
