# Generated by Django 5.2.5 on 2026-08-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_mm_stock_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='category',
            field=models.CharField(choices=[('Laboratory Equipment', 'Laboratory Equipment'), ('Furniture', 'Furniture'), ('Educational Materials', 'Educational Materials'), ('Electronics', 'Electronics'), ('Sports Equipment', 'Sports Equipment'), ('Storage Supplies', 'Storage Supplies'), ('Stationery', 'Stationery'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Safety Equipment', 'Safety Equipment'), ('Art Supplies', 'Art Supplies'), ('Musical Instruments', 'Musical Instruments'), ('IT Equipment', 'IT Equipment'), ('Other', 'Other')], max_length=100),
        ),
    ]
